framework:
    assets:
        packages:
            shop:
                json_manifest_path: '%kernel.project_dir%/public/build/shop/manifest.json'
            admin:
                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
            bijouxTheme:
                json_manifest_path: '%kernel.project_dir%/public/build/bijouxTheme/manifest.json'