imports:
    - { resource: "@DediSyliusSEOPlugin/Resources/config/config.yaml" }
  
sylius_ui:
    events:
        dedi_sylius_seo_plugin.title:
            blocks:
                dedi_seo_title: "@DediSyliusSEOPlugin/Shop/Header/_title.html.twig"