liip_imagine:
    # webp:
    #     generate: true
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        product_block_image:
            filters:
                strip: ~
                thumbnail: { size: [450, 350], mode: inset }
        product_main_image:
            filters:
                strip: ~
                thumbnail: { size: [440, 480], mode: outbound }
        cart_image:
            filters:
                strip: ~
                thumbnail: { size: [150, 150], mode: outbound }
