imports:
    - { resource: "@SyliusInvoicingPlugin/Resources/config/config.yml" }
sylius_mailer:
    emails:
        invoice_generated:
            subject: sylius.emails.invoice_generated.subject
            template: "SyliusInvoicingPlugin/Invoice/Email/invoiceGenerated.html.twig"
